/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiburonesblancos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static tiburonesblancos.Alumnos.getConection;
import static tiburonesblancos.RAlumnos.getConection;
import static tiburonesblancos.TRegistro.getConection;

/**
 *
 * @author Acer
 */
public class Corte extends javax.swing.JFrame {

    /**
     * Creates new form Corte
     */
    public Corte() {
        initComponents();
        
        //Alumnos A=new Alumnos();
        String u =getUsuario();
            System.out.println(u);
            int us = Integer.parseInt(u);
              d2.setText("");
              m2.setText("");
              a2.setText("");        
            if (us == 2) {
             d2.setEnabled(false);
             m2.setEnabled(false);
             a2.setEnabled(false);
            }
    }
static String login="root";
static String password="16070065";
static String url="jdbc:mysql://localhost/tiburonesblancos?characterEncoding=latin1";
PreparedStatement ps;
ResultSet rs;    
public static Connection getConection()
{
Connection conn = null;
    try
           {
              Class.forName ("com.mysql.jdbc.Driver").newInstance ();
               conn = DriverManager.getConnection (url, login, password);               
               System.out.println ("Conexion establecida");   
           }    catch (Exception e)
           {
               System.err.println ("Hubo problema para la conexión"+e);
           }
           
        return conn;
 }
int cont;
public void validar()
{
    
}
 
public String getUsuario() {
        String v = "";
        Connection con = null;
        try {
            con = getConection();
            ps = con.prepareStatement("SELECT idUsuario FROM Usuarios WHERE permisos=? ");
            ps.setString(1, "1");
            rs = ps.executeQuery();
            if (rs.next()) {
                v = (rs.getString("idUsuario"));
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "No se encontro el dato");
               
            }
        } catch (Exception e) {
            System.err.println(e + "Error  :D");
        }
        return v;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTcorte = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        m2 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTcorte = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTcorte.setAutoCreateRowSorter(true);
        jTcorte.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jTcorte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "fecha", "tipo de pago", "folio", "cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTcorte.setGridColor(new java.awt.Color(102, 102, 102));
        jTcorte.setRowHeight(24);
        jTcorte.setSelectionBackground(new java.awt.Color(0, 0, 255));
        jTcorte.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jTcorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTcorteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTcorte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 1370, 560));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 780, 200, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calcular.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calcular.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/calcular2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 750, 80, 80));

        jLabel1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel1.setText("Calcular");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 830, -1, -1));

        d1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        d1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d1KeyTyped(evt);
            }
        });
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 40, -1));

        jLabel8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel8.setText("Dia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel9.setText("Mes:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        m1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        m1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                m1KeyTyped(evt);
            }
        });
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 40, -1));

        jLabel10.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel10.setText("Año:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));

        a1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a1KeyTyped(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 50, -1));

        jLabel15.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel15.setText("Fecha Inicial*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel11.setText("Año:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel12.setText("Dia:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        d2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        d2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d2KeyTyped(evt);
            }
        });
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 40, -1));

        jLabel16.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel16.setText("Fecha Final*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        m2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        m2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                m2KeyTyped(evt);
            }
        });
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 40, -1));

        a2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a2KeyTyped(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 50, -1));

        jLabel13.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel13.setText("Mes:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/recargar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/recargar.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/recargar2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 80, 110, 100));

        jButton3.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Menu.png"))); // NOI18N
        jButton3.setText("Menu");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Menu.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Menu2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 60));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Menu/Alumnos_.jpg"))); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcorteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTcorteMouseClicked
        // TODO add your handling code here:
        /*PreparedStatement ps=null;
        ResultSet rs=null;
        try{
            Connection con=null;
            //Conexion objCon=new Conexion();
            //Connection con = objCon.getConection();
            int Fila =jTAlumnos.getSelectedRow();
            String codigo=jTAlumnos.getValueAt(Fila, 0).toString();

            ps=con.prepareStatement("SELECT idAlumos, nombre, apellidoP, apellidoM FROM Alumos WHERE idAlumos=?");
            ps.setString(1,codigo);
            rs=ps.executeQuery();

            while(rs.next()){
                jtxtIdAlumno.setText(rs.getString("idAlumos"));
                jtxtNombre.setText(rs.getString("nombre"));
                jtxtApellidoP.setText(rs.getString("apellidoP"));
                jtxtApellidoM.setText(rs.getString("ApellidoM"));
            }
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        */
        int i = jTcorte.getSelectedRow();
        TableModel model = jTcorte.getModel();
        /*
        jtxtIdRegistro.setText(model.getValueAt(i, 0).toString());
        jtxtPaquete.setText(model.getValueAt(i, 1).toString());
        jtxtHorario.setText(model.getValueAt(i, 2).toString());
        jtxtCategoria.setText(model.getValueAt(i, 3).toString());
        jTxtCarril.setText(model.getValueAt(i, 4).toString());
        jTxtStatus.setText(model.getValueAt(i, 5).toString());
        */
    }//GEN-LAST:event_jTcorteMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
        jTextField1.setText("$ "+Integer.toString(Sum1+Sum2)+" MXN");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void d1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_d1KeyTyped

    private void m1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_m1KeyTyped

    private void a1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_a1KeyTyped

    private void d2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_d2KeyTyped

    private void m2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_m2KeyTyped

    private void a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_a2KeyTyped
 int Sum1=0,Sum2=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
        Connection con=null;
        String fecha1 = a1.getText()+"-"+m1.getText()+"-"+d1.getText();
        String fecha2 = a2.getText()+"-"+m2.getText()+"-"+d2.getText();
       
        String us;
        us=getUsuario();
        String where="";
        if(us.equals("2"))
        {
            if(!"".equals(d1))
            {
            where= " WHERE "+"fecha='"+fecha1+"'";
            }            
        }        
        else
        {
            if(!"".equals(d1.getText()) && "".equals(d2.getText()))
            {
            where= " WHERE "+"fecha='"+fecha1+"'";
            fecha2=fecha1;
            System.out.println("Solo hay 1");
            }
            
            if(!"".equals(d1.getText()) && !"".equals(d2.getText()))
            {
            where= " WHERE "+"fecha between '"+fecha1+"' and '"+fecha2+"'";
            System.out.println("Solo hay 2");
            }
        }  
        
        
DefaultTableModel modelo =new DefaultTableModel();
jTcorte.setModel(modelo);
        try
        {                    

            PreparedStatement ps= null;
            ResultSet rs=null;
            con=getConection();
            String sql="SELECT fecha, clasificacion, folio, total FROM pagos "+where;
            ps =con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd= rs.getMetaData();
            int cantidadColumnas =rsMd.getColumnCount();
            modelo.addColumn("fecha");
            modelo.addColumn("clasificacion");
            modelo.addColumn("folio");
            modelo.addColumn("total");
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                for(int i=0;i<cantidadColumnas;i++)
                {
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
            

        }
        catch(SQLException e){
            System.err.println(e.toString());
        }
        try
        {
            PreparedStatement ps= null;
            ResultSet rs=null;
            con=getConection();
            String sql="SELECT fecha, clasificacion,folio, cantidad FROM otros_pagos "+where;
            ps =con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd= rs.getMetaData();
            int cantidadColumnas =rsMd.getColumnCount();
            
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                for(int i=0;i<cantidadColumnas;i++)
                {
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
            

        }
        catch(SQLException e){
            System.err.println(e.toString());
        }
         try{
            con=getConection();
            ps=con.prepareStatement("SELECT sum(total) as sum1 from pagos where fecha between ? and ?");
            ps.setString(1,fecha1);
            ps.setString(2,fecha2);
            rs=ps.executeQuery();
            if(rs.next())
            {
                Sum1=( Integer.parseInt(rs.getString("sum1")));                
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(null,"No se encontro el dato");
                //limpiarCajas();
            }
        }catch(Exception e)
        {
            System.err.println(e+"Error 1 :D");
        }
         try{
            con=getConection();
            ps=con.prepareStatement("SELECT sum(cantidad) as sum2 from otros_pagos where fecha between ? and ?");
            ps.setString(1,fecha1);
            ps.setString(2,fecha2);
            rs=ps.executeQuery();
            if(rs.next())
            {
                Sum2=( Integer.parseInt(rs.getString("sum2")));                
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(null,"No se encontro el dato");
                //limpiarCajas();
            }
        }catch(Exception e)
        {
            System.err.println(e+"Error 2 :D");
        } 
        
        //limpiarCajas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu m=new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d2ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTcorte;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    // End of variables declaration//GEN-END:variables
}
