/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiburonesblancos;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import static tiburonesblancos.RPagos.url;
import static tiburonesblancos.TRegistro.getConection;
import static tiburonesblancos.TRegistro.login;
import static tiburonesblancos.TRegistro.password;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Rotros_pagos extends javax.swing.JFrame {

    /**
     * Creates new form Rotros_pagos
     */
    public Rotros_pagos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
        @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imgs/icono.png"));
    return retValue;
    }
    
    
static String login="root";
static String password="16070065";
static String url="jdbc:mysql://localhost/tiburonesblancos?characterEncoding=latin1";
PreparedStatement ps;
ResultSet rs;    
public static Connection getConection()
{
Connection conn = null;
    try
           {
              Class.forName ("com.mysql.jdbc.Driver").newInstance ();
               conn = DriverManager.getConnection (url, login, password);               
               System.out.println ("Conexion establecida");   
           }    catch (Exception e)
           {
               System.err.println ("Hubo problema para la conexión"+e);
           }
           
        return conn;
 }
int cont;
public void validar(){
   
    if(jComboBox1.getSelectedItem().equals("Seleccione")){cont++;}
    if(d6.getText().equals("")){cont++;}
    if(d7.getText().equals("")){cont++;}
    if(d8.getText().equals("")){cont++;}
    if(d9.getText().equals("")){cont++;}
    
    
    
    
}
private void limpiarCajas()
{
   d1.setText(null);
   jComboBox1.setSelectedIndex(0);
   datNombre.setText(null);
   datApellidoP.setText(null);
   d6.setText(null);
   d7.setText(null);
   d8.setText(null);
   d9.setText(null);
   
   d11.setText(null);
   //jCbxDia.setSelectedIndex(0);
   //jCbxDia.setVisible(false);
   //jBDia.setVisible(false);
        
        
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datApellidoP = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        datNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        d11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        d7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        d8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        d9 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        d6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bRegistrar = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datApellidoP.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        datApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datApellidoPActionPerformed(evt);
            }
        });
        datApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datApellidoPKeyTyped(evt);
            }
        });
        getContentPane().add(datApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 310, 200, 40));

        d1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 91, 40));

        jButton1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton1.setText("Buscar Alumno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 370, -1, 40));

        datNombre.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        datNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datNombreActionPerformed(evt);
            }
        });
        datNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datNombreKeyTyped(evt);
            }
        });
        getContentPane().add(datNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 190, 40));

        jLabel1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel1.setText("ID del Alumno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 130, 40));

        jLabel11.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel11.setText("Nombre");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 80, 30));

        jLabel12.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel12.setText("Apellido Paterno");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 280, 150, 30));

        jLabel3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel3.setText("Clasificación*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, 40));

        jComboBox1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Inscripción", "PagosExcepcionales", "OtroPago" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, -1, 40));

        d11.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        d11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d11ActionPerformed(evt);
            }
        });
        getContentPane().add(d11, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 150, 40));

        jLabel16.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel16.setText("Folio");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 60, 30));

        jLabel15.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel15.setText("Fecha*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, -1, 30));

        jLabel8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel8.setText("Dia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, -1, 30));

        d7.setEditable(false);
        d7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        d7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d7KeyTyped(evt);
            }
        });
        getContentPane().add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, 40, 40));

        jLabel9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel9.setText("Mes:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 610, -1, 30));

        d8.setEditable(false);
        d8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        d8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d8KeyTyped(evt);
            }
        });
        getContentPane().add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, 40, 40));

        jLabel10.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel10.setText("Año:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 610, -1, 30));

        d9.setEditable(false);
        d9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        d9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d9KeyTyped(evt);
            }
        });
        getContentPane().add(d9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 610, 50, 40));

        jButton4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton4.setText("Cargar Fecha");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 610, -1, 40));

        d6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        d6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d6ActionPerformed(evt);
            }
        });
        getContentPane().add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 140, 40));

        jButton6.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Menu.png"))); // NOI18N
        jButton6.setText("Menu");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Menu.png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Menu2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        jLabel6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel6.setText("Total $*");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, -1, 40));

        jLabel4.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        jLabel4.setText("Otros Pagos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, -1, -1));

        bRegistrar.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        bRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/AgregarPago.png"))); // NOI18N
        bRegistrar.setText("Registrar");
        bRegistrar.setToolTipText("");
        bRegistrar.setBorderPainted(false);
        bRegistrar.setContentAreaFilled(false);
        bRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/AgregarPago.png"))); // NOI18N
        bRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/AgregarPago2.png"))); // NOI18N
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(bRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 680, 210, 100));

        jLFondo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Menu/Alumnos_.jpg"))); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datApellidoPActionPerformed

    private void datApellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datApellidoPKeyTyped
        // TODO add your handling code here
        //         char c=evt.getKeyChar();
        //      if((c<'a'|| c>'z') && (c<'A'|| c>'Z'))evt.consume();
    }//GEN-LAST:event_datApellidoPKeyTyped

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        if(d1.getText().equals(""))
        {
            try{
                con=getConection();
                ps=con.prepareStatement("SELECT idAlumnos FROM Alumnos WHERE nombre=? AND apellidop=?");//// corregir alumnos en el bd
                ps.setString(1,datNombre.getText());
                ps.setString(2,datApellidoP.getText());
                rs=ps.executeQuery();
                if(rs.next())
                {
                    d1.setText(rs.getString("idAlumnos"));
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"No se encontro el Alumno");
                    datApellidoP.setText(null);
                    datNombre.setText(null);
                }
            }catch(Exception e)
            {
                System.err.println(e+"Error 5 :D");
            }
        }
        else
        {
            try{
                con=getConection();
                ps=con.prepareStatement("SELECT nombre, apellidoP FROM Alumnos WHERE idAlumnos=?");//// corregir alumnos en el bd
                ps.setString(1,d1.getText());
                rs=ps.executeQuery();
                if(rs.next())
                {
                    datNombre.setText(rs.getString("nombre"));
                    datApellidoP.setText(rs.getString("apellidoP"));
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"No se encontro el Alumno");
                    datApellidoP.setText(null);
                    datNombre.setText(null);
                }
            }catch(Exception e)
            {
                System.err.println(e+"Error 5.2 :D");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void datNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datNombreActionPerformed

    private void datNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datNombreKeyTyped
        // TODO add your handling code here:
        //         char c=evt.getKeyChar();
        //      if((c<'a'|| c>'z') && (c<'A'|| c>'Z'))evt.consume();
    }//GEN-LAST:event_datNombreKeyTyped

    private void d7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d7KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_d7KeyTyped

    private void d8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d8KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_d8KeyTyped

    private void d9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d9KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_d9KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        Date fecha = new Date();
        int dia=fecha.getDate();
        int mes=fecha.getMonth();
        int año=fecha.getYear();
        d7.setText(Integer.toString(dia));
        d8.setText(Integer.toString(mes+1));
        d9.setText(Integer.toString(año+1900));

    }//GEN-LAST:event_jButton4ActionPerformed

    private void d6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        // TODO astemdd your handling code here:valil
        cont=0;
        validar();
        if(cont==0)
        {
            String ps3;
            if(!"".equals(d1.getText())){ ps3=d1.getText();}else{ps3=null;}
            String ps4;
            if(!"".equals(datNombre.getText())){ ps4=datNombre.getText();}else{ps4=null;}
            String ps5;
            if(!"".equals(datApellidoP.getText())){ ps5=datApellidoP.getText();}else{ps5=null;}
            String ps7;
            if(!"".equals(d11.getText())){ ps7=d11.getText();}else{ps7=null;}
            Connection con=null;
            try{
                con=getConection();

                ps= con.prepareStatement("INSERT INTO otros_pagos (id_otros_pagos,clasificacion,id_alumno,nombre,apellidoP,cantidad,folio,fecha) VALUES(?,?,?,?,?,?,?,?)");
                ps.setString(1,null);
                ps.setString(2,jComboBox1.getSelectedItem().toString());
                ps.setString(3,ps3);
                ps.setString(4,ps4);
                ps.setString(5,ps5);
                ps.setString(6,d6.getText());
                ps.setString(7,ps7);
                ps.setString(8,d9.getText()+"-"+d8.getText()+"-"+d7.getText());
                
                int res=ps.executeUpdate();
                if(res>0)
                {
                    JOptionPane.showMessageDialog(rootPane,"Pago Registrado");
                    limpiarCajas();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Error al Registrar");
                    limpiarCajas();
                }
                con.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Rellene los campos requeridos");
        }
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void d11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rotros_pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rotros_pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rotros_pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rotros_pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rotros_pagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegistrar;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d11;
    private javax.swing.JTextField d6;
    private javax.swing.JTextField d7;
    private javax.swing.JTextField d8;
    private javax.swing.JTextField d9;
    private javax.swing.JTextField datApellidoP;
    private javax.swing.JTextField datNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
